### ISSUE TITLE
When I start using 1.0.2 , its showing error.

### ISSUE THREAD

**Issue by galibimtiaz** [Commit451/NativeStackBlur#1]
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/commit451/nativestackblur/BuildConfig;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)

**Comment by galibimtiaz** [comment]
Ok , it was solved by cleaning the project.

If anyone having same problem just do this-

Build > Clean Project.

**Comment by Jawnnypoo** [comment]
Thanks for giving the solution!
