### ISSUE TITLE
couldn't find "libblur.so"

### ISSUE THREAD

**Issue by niravdhanani07** [Commit451/NativeStackBlur#4]
Hi @Jawnnypoo 

  When i open activity which used this library, i get below error.

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pip.cameraeffect-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pip.cameraeffect-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libblur.so"
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                          at java.lang.System.loadLibrary(System.java:989)
                                                                          at com.enrique.stackblur.NativeBlurProcess.<clinit>(NativeBlurProcess.java:20)
                                                                          at com.commit451.nativestackblur.NativeStackBlur.process(NativeStackBlur.java:20)
                                                                          at com.waycreon.pip.SelectedImageActivity.makeMaskImage(SelectedImageActivity.java:193)
                                                                          at com.waycreon.pip.SelectedImageActivity.onCreate(SelectedImageActivity.java:163)
                                                                          at android.app.Activity.performCreate(Activity.java:6005)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2555)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:176)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5576)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)`

**Comment by Jawnnypoo** [comment]
Hey can you tell me what device this happened on? It seems like it is a linking error but the library is built for ARM 64 so this is strange. Can you maybe also try with 1.0.4 and see if it is still an issue?

**Comment by Jawnnypoo** [comment]
Any word on this @niravdhanani07 ? Seems like it should work in the latest release.

**Comment by Jawnnypoo** [comment]
Going to go ahead and close this and hopefully it was just a fluke with the build or something.
