### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libblur.so" not found

### ISSUE THREAD

**Issue by SeyedJavadMajidi** [Commit451/NativeStackBlur#7]
Hi!
My Error:
java.lang.UnsatisfiedLinkError: dlopen failed: library "libblur.so" not found

`    java.lang.UnsatisfiedLinkError: dlopen failed: library "libblur.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.enrique.stackblur.NativeBlurProcess.<clinit>(NativeBlurProcess.java:20)
        at com.commit451.nativestackblur.NativeStackBlur.process(NativeStackBlur.java:20)
        at softjam.waycreon.pip.SelectedImageActivity.makeMaskImage(SelectedImageActivity.java:455)
        at softjam.waycreon.pip.SelectedImageActivity.onCreate(SelectedImageActivity.java:398)
        at android.app.Activity.performCreate(Activity.java:8207)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3800)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4003)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8595)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
`

My build.gradle
```
 compileSdkVersion 30
    buildToolsVersion '30.0.3'

    defaultConfig {
        applicationId "XXXXXXXXXXXXXXXXXXXX"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 19
        versionName "1.2"
        multiDexEnabled true
    }

```

**Comment by zainriaz** [comment]
Use new NativeStackBlur 

       allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	    }
        }


 dependencies {
    implementation 'com.github.Commit451:NativeStackBlur:1.0.5'
 
 }

for more details https://githubhelp.com/Commit451/NativeStackBlur

**Comment by SeyedJavadMajidi** [comment]
very tnx :)
